# Hydra Configuration for Graph Clustering Sweep
# === Hydra ===
hydra:
  run:
    dir: .hydra_outputs/clustering/${now:%Y-%m-%d_%H-%M-%S}

# Data paths
data:
  # input_path: "outputs/preprocessing/book_small"
  target_lbl: "char_chat"
  # output_path: "outputs/clustering/book_small"
  input_path: "outputs/preprocessing/book1"
  output_path: "outputs/clustering/book1"


# Clustering method
method:
  feature: "histogram"
  edges_type: "nlfa"
  metric: "CEMD"
  keep_reciprocal: true
  device: "cuda"

  # Parameter sweep ranges

  # cell_sizes: [16, 24, 32]  # Cell size for HOG computation
  # grdt_sigmas: [5]       # Gradient sigma for smoothing
  # nums_bins: [8, 16]        # Number of orientation bins

  epsilons: [0.00025, 0.00038, .0005]
  # epsilons: [0.0005]
  # gammas: [1.0, 1.25]
  gammas: [1.0]

  cell_sizes: [22]  # Cell size for HOG computation
  # cell_sizes: [48]  # Cell size for HOG computation
  normalization_methods : ['patch'] # patch >> all
  grdt_sigmas: [5]       # Gradient sigma for smoothing
  nums_bins: [16]        # Number of orientation bins


  # == __ Post-clustering refinement __ ==
  enable_chat_split: true           # split clusters with mixed CHAT labels
  chat_split_purity_threshold: 1 # skip if dominant label >= this fraction
  chat_split_min_size: 3            # clusters smaller than this are never split
  chat_split_min_label_count: 2     # CHAT label needs >= this many patches

  enable_hapax_association: true     # merge singletons into matching clusters
  hapax_min_confidence: 0.5          # ignore hapax with CHAT conf below this
  hapax_max_dissimilarity: null      # null = adaptive (per-cluster median)

  enable_glossary: true              # generate character glossary


# Reporter (injected into graphClusteringSweep)
reporter:
  _target_: src.clustering.clustering_sweep_report.ClusteringSweepReporter
  target_lbl: ${data.target_lbl}
  split_linkage_method: "average"
  split_thresholds: [21.5]
  embed_images: true
  image_dpi: 75
  use_jpeg: false
  jpeg_quality: 70

# Refinement pipeline (injected into graphClusteringSweep)
refinement_steps:
  - _target_: src.clustering.refinement.HausdorffSplitStep
    thresholds: [21.5]
    linkage_method: "average"
    min_cluster_size: 5
    batch_size: 256

  - _target_: src.clustering.refinement.OCRRematchStep
    max_cluster_size: 3

  - _target_: src.clustering.refinement.LabelSplitStep
    min_label_size: 2
