# Hydra Configuration for Graph Clustering Sweep
# === Hydra ===
hydra:
  run:
    dir: .hydra_results/clustering/${now:%Y-%m-%d_%H-%M-%S}

# Data paths
data:
  # input_path: "results/preprocessing/book_small"
  # Ground-truth column for final evaluation. Options:
  #   "char_chat"          — raw OCR predictions (CHAT model)
  #   "char_transcription" — aligned transcription labels
  #   "char_consensus"     — only where OCR and transcription agree
  target_lbl: "char_consensus"
  # Label column used during the hyperparameter sweep (config selection).
  # Kept separate from target_lbl to avoid methodological leak: the
  # cross-validated consensus should only be used for evaluation, not
  # for choosing the best configuration.
  sweep_lbl: "char_chat"
  # output_path: "results/clustering/book_small"
  input_path: "results/preprocessing/book1"
  output_path: "results/clustering/book1"


# ── Shared anchors ──────────────────────────────────────────────
_split_thresholds: &split_thresholds [10, 14, 17, 19, 21, 21.5, 22, 24, 28, 35]


# Clustering method
method:
  feature: "histogram"
  edges_type: "nlfa"
  metric: "CEMD"
  keep_reciprocal: true
  # Ablation A4: sweep over reciprocal edge filtering.
  # Set to [true, false] to compare reciprocal vs. non-reciprocal edges.
  keep_reciprocals: [true]
  device: "cuda"

  # Parameter sweep ranges

  # HOG ablation (A1): uncomment extra values to sweep.
  # cell_sizes: [16, 22, 32]
  # grdt_sigmas: [3, 5, 7]
  # nums_bins: [8, 16]

  # Partition types for Leiden algorithm (A2):
  #   "RBConfiguration" — modularity-based (null model); gamma ≈ 1.0 is standard
  #   "CPM"             — Constant Potts Model (absolute density); needs much
  #                        smaller gamma (0.01–0.5) for sparse graphs
  # The gamma range below covers both regimes: low values for CPM,
  # higher values for RBConfiguration.
  partition_types: ["CPM", "RBConfiguration"]

  epsilons: [.00015, 0.0002, 0.00025, 0.0005, 0.001, 0.002, 0.005]
  # epsilons: [0.0005]
  # gammas: [1.0, 1.25]
  gammas: [0.025, 0.06, 0.1, 0.25, 0.5, 1.0, 2.0]


  cell_sizes: [22]                   # Cell size for HOG computation
  normalization_methods: ['patch']   # patch >> all
  grdt_sigmas: [5]                   # Gradient sigma for smoothing
  nums_bins: [16]                    # Number of orientation bins

  enable_glossary: true              # generate character glossary


# Reporter (injected into graphClusteringSweep)
reporter:
  _target_: src.clustering.clustering_sweep_report.ClusteringSweepReporter
  target_lbl: ${data.target_lbl}
  split_linkage_method: "average"
  split_thresholds: *split_thresholds
  embed_images: true
  image_dpi: 75
  use_jpeg: false
  jpeg_quality: 70

# Refinement pipeline (injected into graphClusteringSweep)
refinement_steps:
  - _target_: src.clustering.refinement.HausdorffSplitStep
    thresholds: *split_thresholds
    linkage_method: "average"
    min_cluster_size: 3
    batch_size: 256

  - _target_: src.clustering.refinement.LabelSplitStep
    min_label_size: 2
