# config.yaml - Hydra configuration for GlobalPipeline

_target_: src.ocr.pipeline.GlobalPipeline

device: cuda  # 'cuda' or 'cpu'

# CRAFT Text Detector Configuration
#! Does not need to be tweaked!
craftDetectorParams:
  _target_: src.ocr.params.craftParams
  
  # Detection parameters
  mag_ratio: 5.0
  canvas_size: 1280
  interpolation: bilinear
    
  # Model checkpoint
  chckpt: models/craft/craft_mlt_25k.pth

# CRAFT Output Analysis Configuration
craftComponentAnalysisParams:
  _target_: src.ocr.params.craftComponentsParams
  
  # Connected components extraction
  text_threshold: 0.6  #! Threshold on CRAFT score map for seed detection
  connectivity: 8  #? 4 or 8

  # Dual-threshold watershed: allows basins to expand into moderate-score areas
  # where radicals of composite characters (e.g. 蒸) may have lower CRAFT scores.
  # Set to null to use text_threshold for both seeds and mask (original behavior).
  mask_threshold: null

  # Link score combination: bridges gaps between sub-components of composite
  # characters using CRAFT's affinity map. Set to null to disable (recommended
  # until validated on your data). See craft_utils.py:29 for reference.
  link_threshold: null

  #! Component filtering
  min_area: 18  #!Remove components smaller than this

  # Component merging
  min_dist: 8.0  #!Merge components closer than this (pixels)
  
  # Unary potential (currently unused)
  characteristic_distance: 5.0
  neighborhood_radius: 50

# Image Binarization & Component Analysis Configuration
imageComponentsPipelineParams:
  _target_: src.ocr.params.imageComponentsParams
  
  # Binarization
  threshold: otsu  # 'otsu' or float in [0, 1]
  
  # Filter elongated line-like components
  min_image_component_aspect_ratio: 20.0  # Aspect ratio > this = line
  min_image_component_axis_major_length_criterion: 100.0  # Length > this = line
  
  # Spatial filtering (distance from text regions)
  similarity_threshold: -10.0  #! euclidean distance threshold
  similarity_metric: mahalanobis  # 'mahalanobis' or 'euclidean'
  
  # Character bounding box constraints
  min_box_size: [30, 30]  # [width, height] in pixels
  max_box_size: [150, 150]
  
  # Character area constraint
  min_area: 200

  cc_filtering: true
  cc_distance_threshold: 50
  cc_min_comp_size: 4000
