# config/config.yaml
defaults:
  - vectorizer: default
  
# === Data ===
data:
  image_folder: "data/datasets/book1"
  comps_folder: "outputs/book1-complete"
  output_path: "outputs/processed_patches_book1complete"

verbose: false
return_plots: false

# === Patch Preprocessor ===
patch_preprocessor:
  _target_: src.patch_processing.PatchPreprocessing
  verbose: ${verbose}
  output_viz: preprocessing_outputs/

  reading_order:
    _target_: src.layout_analysis.parsing.ReadingOrder
    min_col_area: 50

  # Ink Filter
  ink_filter:
    _target_: src.patch_processing.InkFilter
    min_size_black: 10
    min_size_white: 5
  
  # Vectorizer
  vectorizer: ${vectorizer}

  # === CHAT column-level OCR (replaces Qwen + renderer) ===
  chat_model:
    _target_: src.ocr.chat.ModelWrapper
    rec_model_path: "models/chat/chat_rec.mlmodel"
    device: null    # auto-detect cuda/cpu
    pad: 16

  # --- OLD: renderer-based OCR (commented out) ---
  # ocr_model_configs:
  #   - _target_: src.ocr.wrappers.QwenOCRSingle
  #     _partial_: true
  #     max_pixels: 786432
  #     device_map: auto
  #
  # ocr_renderer:
  #   _target_: src.patch_processing.Renderer
  #   scale: 1.0
  #   dpi: 256
  #   bin_thresh: 128
  #   pad_to_multiple: null
  #   verbose: ${verbose}
  
  # HOG Renderer (unchanged — still needed for HOG descriptors)
  hog_renderer:
    _target_: src.patch_processing.Renderer
    scale: 1.0
    dpi: 256
    bin_thresh: 128
    pad_to_multiple: 24
    verbose: ${verbose}
  
  # HOG Parameters
  hog_params:
    _target_: src.patch_processing.HOGParameters
    device: cpu
    C: 1
    partial_output: false
    method: gaussian
    grdt_sigma: 5
    ksize_factor: 6
    cell_height: 24
    cell_width: 24
    num_bins: 16
    threshold: 0.2
    normalize: patch

# === Hydra ===
hydra:
  run:
    dir: .hydra_outputs/${now:%Y-%m-%d_%H-%M-%S}