# config/config.yaml
defaults:
  - vectorizer: default
  
# === Data ===
data:
  image_folder: "data/datasets/book1"
  comps_folder: "outputs/book1-complete"
  output_path: "outputs/processed_patches_book1complete"

verbose: true
return_plots: false

# === Patch Preprocessor ===
patch_preprocessor:
  _target_: src.patch_processing.PatchPreprocessing
  verbose: ${verbose}
  output_viz: preprocessing_outputs/

  reading_order:
    _target_: src.layout_analysis.parsing.ReadingOrder
    min_col_area: 50

  # Ink Filter
  ink_filter:
    _target_: src.patch_processing.InkFilter
    min_size_black: 10
    min_size_white: 5
  
  # Vectorizer
  vectorizer: ${vectorizer}

  # OCR Models
  ocr_model_configs:
    - _target_: src.ocr.wrappers.ChatOCR
      _partial_: true

    # - _target_: src.ocr.wrappers.QwenOCR
    #   _partial_: true
    #   nrows: 1
    #   ncols: 4
    #   max_pixels: 1048576 # '1024 x 1024' -> we will use less in practice
    #   device_map: auto
    # - _target_: src.ocr.wrappers.EasyOCRModel

  
  # OCR Renderer
  ocr_renderer:
    _target_: src.patch_processing.Renderer
    scale: 1.0
    dpi: 256
    bin_thresh: 128
    pad_to_multiple: null
    verbose: ${verbose}
  
  # HOG Renderer
  hog_renderer:
    _target_: src.patch_processing.Renderer
    scale: 1.0
    dpi: 256
    bin_thresh: 128
    pad_to_multiple: 24
    verbose: ${verbose}
  
  # HOG Parameters
  hog_params:
    _target_: src.patch_processing.HOGParameters
    device: cpu
    C: 1                          # Use grayscale images
    partial_output: false         # Also output the resized images, their gradient orientation and magnitude
    method: gaussian              # Use gaussian smoothing to compute the gradients
    grdt_sigma: 5                 # Std of the smoothing
    ksize_factor: 6               # Size of the smoothing kernel = factor * std
    cell_height: 24               # Size of the cells to compute the histograms
    cell_width: 24
    num_bins: 16                  # Number of bins
    threshold: 0.2                # Clip the values of the descriptor
    normalize: patch              # Normalize at patch-level. SIFT uses cell-level descriptor normalization

# === Hydra ===
hydra:
  run:
    dir: .hydra_outputs/${now:%Y-%m-%d_%H-%M-%S}