_target_: src.vectorization.BinaryShapeVectorizer

config:
  _target_: src.vectorization.VectorizerConfig

  executable_path: ./build/main
  
  # Vectorization
  # threshold: null  # null = auto Otsu
  smoothing_scale: 1
  accuracy_threshold: 1
  refinement_iterations: 0
  output_type: shape_merged # outline, shape, outline_merged, shape_merged
  
  # Output
  return_svg: true  # Returns SVG objects by default
  return_svg_string: false
  return_rendered: false
  save_dir: ./outputs_svg
  
  # Rendering (if return_rendered=true)
  output_size: [512, 512]
  background_color: [255, 255, 255, 255]
  dpi: 2048
  scale: 1.0
  output_format: L  # PIL format
  
  # Batch processing
  n_jobs: -1  # all CPUs
  show_progress: true
  chunk_size: 100
  
  # Streaming (returns generator that yields (idx, result) tuples)
  stream_results: true
  stream_parallel: true  # Uses multiprocessing with streaming


# Post-processing

# For 512x512 rendering
# min_size_black: 1200
# min_size_white: 320
# border_min_size: 3400